### ISSUE TITLE
Suggested changes to French translation

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/R-Instat-Translations#1]
Use this issue to make a small suggested change as an alternative to editing the translation file.
Add any suggested changes as a comment below. 
Please include:
1. Location of the string i.e. which dialog
2. String in English
3. Current string in French
4. New string in French
5. Reason for the suggested change.

**Comment by Wycklife** [comment]
For the New data frame dialog, when you click on the Empty option, it displays rows and columns for the English translation . For the french translation, `rows` becomes `Nombre de ligne` which is much longer. I suggested we just have the translation for `rows` which I think is `ligne` instead of the entire phrase.

**Comment by dannyparsons** [comment]
@rdstern @volloholic can someone confirm if this is a sensible change? Should it be `lignes` for plural?

**Comment by rdstern** [comment]
Yes, it should be lignes.  We should also be remembering to ask Nicholas some of these questions.  Perhaps he should be on github.

**Comment by dannyparsons** [comment]
`Data Options` translated to `Options de données` on the selector which is not visible e.g.
![image](https://user-images.githubusercontent.com/11214914/52325008-7ac4fd00-29f4-11e9-8f2c-f2fad088cc43.png)

Before we make the button bigger/wider is there a better translation that would be shorter?

**Comment by dannyparsons** [comment]
On the image as above, `Data Frame` is translated as `Trame de données`. Is this appropriate or not?

**Comment by Muthenya** [comment]
Similarly for the Combine Factors dialog, the `separator `has two possible translations. I'm not sure why but I  believe one will do.

![image](https://user-images.githubusercontent.com/32125033/52325981-1d32af80-29f8-11e9-8eaa-e666ef67aab0.png)

**Comment by nicogreu** [comment]
Hello!
- Instead of "Options de données", I think I would just write "**options**".
- And I think the usual translation for "data frame" in French would be "**tableau de données**" instead of "trame de données". If it's too long, I would maybe just go with "**données**" if you're ok that it doesn't emphasise the fact that it is an object.
- Instead of the long "Caractère de separation", I would go for "**séparateur**".

**Comment by dannyparsons** [comment]
Thanks @trueNico!
I think the problem with just `options` is that there might be other buttons for options on the dialog so we wanted something specific for the data options. But we can widen the button slightly if that's no alternative.

Thanks for the others that sounds good. I'll update those.

**Comment by dannyparsons** [comment]
For `Options de données` I've reduced the font size and it now fits and is still readable I think.

**Comment by dannyparsons** [comment]
I've realised we should have a single issue for each translation suggestion so I'm closing this now. Issues can be opened for individual suggestions now.

**Comment by dannyparsons** [comment]
I've created an issue template for suggesting a change to a translation
